version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
        - "27018:27018"
    volumes:
        - mongo_data:/data/db
  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://productdb:27017"
    depends_on:
      - productdb
    ports:
      - "5000:80"
volumes:
  mongo_data: